/********************************************/
/*  author: Mohamed Walid                   */
/*  version: V02                            */
/*  Date: 1 NOV 2023                        */
/*  SWC : TWI                               */
/********************************************/



#ifndef		TWI_PRIV_H
#define		TWI_PRIV_H


#define		TWI_MASTER_NODE		1
#define 	TWI_SLAVE_NODE		2


#define		TWI_SPEED_400KHZ    400
#define		TWI_SPEED_300KHZ    300
#define		TWI_SPEED_200KHZ    200
#define		TWI_SPEED_100KHZ    100

#define		TWI_GC_ENABLED		1
#define		TWI_GC_DISABLED		0


#define 	TWI_START_CONDITION					0xE4
#define		TWI_MASTER_TRANSMIT					0x84			// NO ACK
#define		TWI_STOP_CONDITION					0xD4
#define		TWI_MASTER_TRANSMIT_WITH_ACK		0xC4


#define		TWI_TWSR_MASK			0xF8


#define 	TWI_WRITE_OPERATION			0
#define		TWI_READ_OPERATION			1

#define		TWI_SLAVE_RECEIVE			0x44

#define		TWI_COUNTER_TIMEOUT			65534


// slave status begins from 0x60

#define		TWI_START_CONDITION_TRANSMITTED							0x08
#define		TWI_REPEATED_START_CONDITION_TRANSMITTED				0x10
#define		TWI_SLA_W_TRANSMITTED_ACK_RECEIVED				 		0x18
#define		TWI_SLA_W_TRANSMITTED_NACK_RECEIVED						0x20
#define		TWI_DATA_TRANSMITTED_ACK_RECEIVED_AS_MASTER				0x28
#define		TWI_DATA_TRANSMITTED_NACK_RECEIVED_AS_MASTER			0x30
#define		TWI_BUS_LOST_IN_SLA_W_OR_DATA							0x38
#define		TWI_BUS_LOST_IN_SLA_R_OR_NACK							0x38
#define		TWI_SLA_R_TRANSMITTED_ACK_RECEIVED						0x40
#define		TWI_SLA_R_TRANSMITTED_NACK_RECEIVED						0x48
#define		TWI_DATA_RECEIVED_WITH_ACK_RETURNED						0x50						
#define		TWI_DATA_RECEIVED_WITH_NACK_RETURNED					0x58
#define		TWI_SLA_W_RECEIVED_WITH_ACK_RETURNED					0x60
#define		TWI_BUS_LOST_SLA_W_RECEIVED_ACK_RETURNED				0x68
#define		TWI_GENERAL_CALL_RECEIVED_ACK_RETURNED					0x70
#define		TWI_BUS_LOST_GENERAL_CALL_RECEIVED_ACK_RETURNED			0x78
#define		TWI_SLA_W_RECEIVED_DATA_RECEIVED_ACK_RETURNED			0x80
#define		TWI_SLA_W_RECEIVED_DATA_RECEIVED_NACK_RETURNED			0x88
#define		TWI_GENERAL_CALL_RECEIVED_DATA_RECEIVED_ACK_RETURNED	0x90
#define		TWI_GENERAL_CALL_RECEIVED_DATA_RECEIVED_NACK_RETURNED	0x98
#define		TWI_STOP_OR_REPEATED_START_CONDITION_RECEIVED			0xA0
#define		TWI_SLA_R_RECEIVED_ACK_RETURNED							0xA8
#define		TWI_BUS_LOST_SLA_R_RECEIVED_ACK_RETURNED				0xB0
#define		TWI_DATA_TRANSMITTED_ACK_RECEIVED_AS_SLAVE				0xB8
#define		TWI_DATA_TRANSMITTED_NACK_RECEIVED_AS_SLAVE				0xC0
#define		TWI_LAST_DATA_TRANSMITTED_ACK_RECEIVED					0xC8


#endif
